import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/styles.css'
import './styles/coloring-gradient.css'
import './styles/de-modern.css'
import './styles/custom-font-3.css'
import './styles/colors/scheme-12.css'
import 'bootstrap/dist/css/bootstrap.css'
import {MarketplaceProvider} from '../../contexts/Marketplace'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {

  return (
    <html lang="en">
      <body>
      <MarketplaceProvider>
          {children}
      </MarketplaceProvider>
      </body>
    </html>
  )
}
