import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/styles.css'
import './styles/coloring-gradient.css'
import './styles/de-modern.css'
import './styles/custom-font-3.css'
import './styles/colors/scheme-12.css'
import 'bootstrap/dist/css/bootstrap.css'
// install animate css

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
